server.port=${PORT:8080}
gemini.api.key=AIzaSyAFuqytbdvvKv8H3BWQqu-TZOcEl-E2v1k
google.search.api.key=AIzaSyCxCxcMnB3g7KN1h_DOc7T5N9k4fCqLrTU
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
